spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/





